version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: assignee
        min:
          count: 1
      - do: approvals
        min:
          count: 1
        block:
          changes_requested: true
      - do: title
        must_include:
          regex: '^[a-z]+(\([a-z-]+\))?: [a-z]{1}.+$'

  - when: schedule.repository
    validate:
      - do: stale
        days: 20
        type: pull_request, issues
    pass:
      - do: comment
        payload:
          body: This is old. Is it still relevant?
