---
theme: minimal-mistakes-jekyll
url: "//barissencan.com"
title: Isair's Website
description: Where everybody knows your name.
google_analytics: UA-20758307-1
disqus_shortname:
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:categories/:title/"
paginate: 5
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
gems:
- jekyll-sitemap
- jekyll-paginate
- jekyll-gist
- jekyll-feed
- jekyll-admin
include:
- ".htaccess"
exclude:
- "*.less"
- ".vscode"
- ".asset-cache"
- ".bundle"
- vendor
- ".jekyll-assets-cache"
- ".sass-cache"
- CHANGELOG
- Gemfile
- LICENSE
- README
- node_modules
- package.json
